name: CI

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

  workflow_dispatch:

concurrency:
  group: ci-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Install GDScript Toolkit
        run: |
          pip install "gdtoolkit==4.*"

      - name: Lint
        run: |
          gdlint .

      - name: Format Check
        run: |
          gdformat --check .

  unit-test:
    # if: false # skip job if no tests exist
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      actions: write
      checks: write
      contents: write
      pull-requests: write
      statuses: write

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - uses: MikeSchulze/gdUnit4-action@v1.1.1
        with:
          godot-version: "4.4.1"
          paths: |
            res://scripts/
            res://tests/
          timeout: 5
          report-name: test_report.xml
